import { PokemonDetail } from '@types';

const getSpriteUrl = (id: number): string => {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
};

export const POKEMON: PokemonDetail[] = [
  {
    id: '#001',
    sprite: getSpriteUrl(1),
    name: 'Bulbasaur',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 253,
  },
  {
    id: '#002',
    sprite: getSpriteUrl(2),
    name: 'Ivysaur',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 325,
  },
  {
    id: '#003',
    sprite: getSpriteUrl(3),
    name: 'Venusaur',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 425,
  },
  {
    id: '#004',
    sprite: getSpriteUrl(4),
    name: 'Charmander',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 249,
  },
  {
    id: '#005',
    sprite: getSpriteUrl(5),
    name: 'Charmeleon',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 325,
  },
  {
    id: '#006',
    sprite: getSpriteUrl(6),
    name: 'Charizard',
    typeOne: 'Fire',
    typeTwo: 'Flying',
    totalBaseStat: 425,
  },
  {
    id: '#007',
    sprite: getSpriteUrl(7),
    name: 'Squirtle',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 250,
  },
  {
    id: '#008',
    sprite: getSpriteUrl(8),
    name: 'Wartortle',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 325,
  },
  {
    id: '#009',
    sprite: getSpriteUrl(9),
    name: 'Blastoise',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 425,
  },
  {
    id: '#010',
    sprite: getSpriteUrl(10),
    name: 'Caterpie',
    typeOne: 'Bug',
    typeTwo: null,
    totalBaseStat: 175,
  },
  {
    id: '#011',
    sprite: getSpriteUrl(11),
    name: 'Metapod',
    typeOne: 'Bug',
    typeTwo: null,
    totalBaseStat: 180,
  },
  {
    id: '#012',
    sprite: getSpriteUrl(12),
    name: 'Butterfree',
    typeOne: 'Bug',
    typeTwo: 'Flying',
    totalBaseStat: 305,
  },
  {
    id: '#013',
    sprite: getSpriteUrl(13),
    name: 'Weedle',
    typeOne: 'Bug',
    typeTwo: 'Poison',
    totalBaseStat: 175,
  },
  {
    id: '#014',
    sprite: getSpriteUrl(14),
    name: 'Kakuna',
    typeOne: 'Bug',
    typeTwo: 'Poison',
    totalBaseStat: 180,
  },
  {
    id: '#015',
    sprite: getSpriteUrl(15),
    name: 'Beedrill',
    typeOne: 'Bug',
    typeTwo: 'Poison',
    totalBaseStat: 305,
  },
  {
    id: '#016',
    sprite: getSpriteUrl(16),
    name: 'Pidgey',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 216,
  },
  {
    id: '#017',
    sprite: getSpriteUrl(17),
    name: 'Pidgeotto',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 299,
  },
  {
    id: '#018',
    sprite: getSpriteUrl(18),
    name: 'Pidgeot',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 399,
  },
  {
    id: '#019',
    sprite: getSpriteUrl(19),
    name: 'Rattata',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 218,
  },
  {
    id: '#020',
    sprite: getSpriteUrl(20),
    name: 'Raticate',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 343,
  },
  {
    id: '#021',
    sprite: getSpriteUrl(21),
    name: 'Spearow',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 231,
  },
  {
    id: '#022',
    sprite: getSpriteUrl(22),
    name: 'Fearow',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 381,
  },
  {
    id: '#023',
    sprite: getSpriteUrl(23),
    name: 'Ekans',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 234,
  },
  {
    id: '#024',
    sprite: getSpriteUrl(24),
    name: 'Arbok',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 359,
  },
  {
    id: '#025',
    sprite: getSpriteUrl(25),
    name: 'Pikachu',
    typeOne: 'Electric',
    typeTwo: null,
    totalBaseStat: 260,
  },
  {
    id: '#026',
    sprite: getSpriteUrl(26),
    name: 'Raichu',
    typeOne: 'Electric',
    typeTwo: null,
    totalBaseStat: 395,
  },
  {
    id: '#027',
    sprite: getSpriteUrl(27),
    name: 'Sandshrew',
    typeOne: 'Ground',
    typeTwo: null,
    totalBaseStat: 280,
  },
  {
    id: '#028',
    sprite: getSpriteUrl(28),
    name: 'Sandslash',
    typeOne: 'Ground',
    typeTwo: null,
    totalBaseStat: 405,
  },
  {
    id: '#029',
    sprite: getSpriteUrl(29),
    name: 'Nidoran♀',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 235,
  },
  {
    id: '#030',
    sprite: getSpriteUrl(30),
    name: 'Nidorina',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 310,
  },
  {
    id: '#031',
    sprite: getSpriteUrl(31),
    name: 'Nidoqueen',
    typeOne: 'Poison',
    typeTwo: 'Ground',
    totalBaseStat: 410,
  },
  {
    id: '#032',
    sprite: getSpriteUrl(32),
    name: 'Nidoran♂',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 233,
  },
  {
    id: '#033',
    sprite: getSpriteUrl(33),
    name: 'Nidorino',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 310,
  },
  {
    id: '#034',
    sprite: getSpriteUrl(34),
    name: 'Nidoking',
    typeOne: 'Poison',
    typeTwo: 'Ground',
    totalBaseStat: 410,
  },
  {
    id: '#035',
    sprite: getSpriteUrl(35),
    name: 'Clefairy',
    typeOne: 'Fairy',
    typeTwo: null,
    totalBaseStat: 258,
  },
  {
    id: '#036',
    sprite: getSpriteUrl(36),
    name: 'Clefable',
    typeOne: 'Fairy',
    typeTwo: null,
    totalBaseStat: 383,
  },
  {
    id: '#037',
    sprite: getSpriteUrl(37),
    name: 'Vulpix',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 249,
  },
  {
    id: '#038',
    sprite: getSpriteUrl(38),
    name: 'Ninetales',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 424,
  },
  {
    id: '#039',
    sprite: getSpriteUrl(39),
    name: 'Jigglypuff',
    typeOne: 'Normal',
    typeTwo: 'Fairy',
    totalBaseStat: 225,
  },
  {
    id: '#040',
    sprite: getSpriteUrl(40),
    name: 'Wigglytuff',
    typeOne: 'Normal',
    typeTwo: 'Fairy',
    totalBaseStat: 350,
  },
  {
    id: '#041',
    sprite: getSpriteUrl(41),
    name: 'Zubat',
    typeOne: 'Poison',
    typeTwo: 'Flying',
    totalBaseStat: 215,
  },
  {
    id: '#042',
    sprite: getSpriteUrl(42),
    name: 'Golbat',
    typeOne: 'Poison',
    typeTwo: 'Flying',
    totalBaseStat: 390,
  },
  {
    id: '#043',
    sprite: getSpriteUrl(43),
    name: 'Oddish',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 255,
  },
  {
    id: '#044',
    sprite: getSpriteUrl(44),
    name: 'Gloom',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 320,
  },
  {
    id: '#045',
    sprite: getSpriteUrl(45),
    name: 'Vileplume',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 390,
  },
  {
    id: '#046',
    sprite: getSpriteUrl(46),
    name: 'Paras',
    typeOne: 'Bug',
    typeTwo: 'Grass',
    totalBaseStat: 240,
  },
  {
    id: '#047',
    sprite: getSpriteUrl(47),
    name: 'Parasect',
    typeOne: 'Bug',
    typeTwo: 'Grass',
    totalBaseStat: 0,
  },
  {
    id: '#048',
    sprite: getSpriteUrl(48),
    name: 'Venonat',
    typeOne: 'Bug',
    typeTwo: 'Poison',
    totalBaseStat: 345,
  },
  {
    id: '#049',
    sprite: getSpriteUrl(49),
    name: 'Venomoth',
    typeOne: 'Bug',
    typeTwo: 'Poison',
    totalBaseStat: 375,
  },
  {
    id: '#050',
    sprite: getSpriteUrl(50),
    name: 'Diglett',
    typeOne: 'Ground',
    typeTwo: null,
    totalBaseStat: 230,
  },
  {
    id: '#051',
    sprite: getSpriteUrl(51),
    name: 'Dugtrio',
    typeOne: 'Ground',
    typeTwo: null,
    totalBaseStat: 355,
  },
  {
    id: '#052',
    sprite: getSpriteUrl(52),
    name: 'Meowth',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 250,
  },
  {
    id: '#053',
    sprite: getSpriteUrl(53),
    name: 'Persian',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 375,
  },
  {
    id: '#054',
    sprite: getSpriteUrl(54),
    name: 'Psyduck',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 255,
  },
  {
    id: '#055',
    sprite: getSpriteUrl(55),
    name: 'Golduck',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 405,
  },
  {
    id: '#056',
    sprite: getSpriteUrl(56),
    name: 'Mankey',
    typeOne: 'Fighting',
    typeTwo: null,
    totalBaseStat: 260,
  },
  {
    id: '#057',
    sprite: getSpriteUrl(57),
    name: 'Primeape',
    typeOne: 'Fighting',
    typeTwo: null,
    totalBaseStat: 385,
  },
  {
    id: '#058',
    sprite: getSpriteUrl(58),
    name: 'Growlithe',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 280,
  },
  {
    id: '#059',
    sprite: getSpriteUrl(59),
    name: 'Arcanine',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 455,
  },
  {
    id: '#060',
    sprite: getSpriteUrl(60),
    name: 'Poliwag',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 260,
  },
  {
    id: '#061',
    sprite: getSpriteUrl(61),
    name: 'Poliwhirl',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 335,
  },
  {
    id: '#062',
    sprite: getSpriteUrl(62),
    name: 'Poliwrath',
    typeOne: 'Water',
    typeTwo: 'Fighting',
    totalBaseStat: 410,
  },
  {
    id: '#063',
    sprite: getSpriteUrl(63),
    name: 'Abra',
    typeOne: 'Psychic',
    typeTwo: null,
    totalBaseStat: 255,
  },
  {
    id: '#064',
    sprite: getSpriteUrl(64),
    name: 'Kadabra',
    typeOne: 'Psychic',
    typeTwo: null,
    totalBaseStat: 330,
  },
  {
    id: '#065',
    sprite: getSpriteUrl(65),
    name: 'Alakazam',
    typeOne: 'Psychic',
    typeTwo: null,
    totalBaseStat: 405,
  },
  {
    id: '#066',
    sprite: getSpriteUrl(66),
    name: 'Machop',
    typeOne: 'Fighting',
    typeTwo: null,
    totalBaseStat: 270,
  },
  {
    id: '#067',
    sprite: getSpriteUrl(67),
    name: 'Machoke',
    typeOne: 'Fighting',
    typeTwo: null,
    totalBaseStat: 345,
  },
  {
    id: '#068',
    sprite: getSpriteUrl(68),
    name: 'Machamp',
    typeOne: 'Fighting',
    typeTwo: null,
    totalBaseStat: 420,
  },
  {
    id: '#069',
    sprite: getSpriteUrl(69),
    name: 'Bellsprout',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 270,
  },
  {
    id: '#070',
    sprite: getSpriteUrl(70),
    name: 'Weepinbell',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 345,
  },
  {
    id: '#071',
    sprite: getSpriteUrl(71),
    name: 'Victreebel',
    typeOne: 'Grass',
    typeTwo: 'Poison',
    totalBaseStat: 420,
  },
  {
    id: '#072',
    sprite: getSpriteUrl(72),
    name: 'Tentacool',
    typeOne: 'Water',
    typeTwo: 'Poison',
    totalBaseStat: 285,
  },
  {
    id: '#073',
    sprite: getSpriteUrl(73),
    name: 'Tentacruel',
    typeOne: 'Water',
    typeTwo: 'Poison',
    totalBaseStat: 435,
  },
  {
    id: '#074',
    sprite: getSpriteUrl(74),
    name: 'Geodude',
    typeOne: 'Rock',
    typeTwo: 'Ground',
    totalBaseStat: 270,
  },
  {
    id: '#075',
    sprite: getSpriteUrl(75),
    name: 'Graveler',
    typeOne: 'Rock',
    typeTwo: 'Ground',
    totalBaseStat: 345,
  },
  {
    id: '#076',
    sprite: getSpriteUrl(76),
    name: 'Golem',
    typeOne: 'Rock',
    typeTwo: 'Ground',
    totalBaseStat: 420,
  },
  {
    id: '#077',
    sprite: getSpriteUrl(77),
    name: 'Ponyta',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 345,
  },
  {
    id: '#078',
    sprite: getSpriteUrl(78),
    name: 'Rapidash',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 420,
  },
  {
    id: '#079',
    sprite: getSpriteUrl(79),
    name: 'Slowpoke',
    typeOne: 'Water',
    typeTwo: 'Psychic',
    totalBaseStat: 275,
  },
  {
    id: '#080',
    sprite: getSpriteUrl(80),
    name: 'Slowbro',
    typeOne: 'Water',
    typeTwo: 'Psychic',
    totalBaseStat: 390,
  },
  {
    id: '#081',
    sprite: getSpriteUrl(81),
    name: 'Magnemite',
    typeOne: 'Electric',
    typeTwo: 'Steel',
    totalBaseStat: 270,
  },
  {
    id: '#082',
    sprite: getSpriteUrl(82),
    name: 'Magneton',
    typeOne: 'Electric',
    typeTwo: 'Steel',
    totalBaseStat: 395,
  },
  {
    id: '#083',
    sprite: getSpriteUrl(83),
    name: 'Farfetch',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 290,
  },
  {
    id: '#084',
    sprite: getSpriteUrl(84),
    name: 'Doduo',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 275,
  },
  {
    id: '#085',
    sprite: getSpriteUrl(85),
    name: 'Dodrio',
    typeOne: 'Normal',
    typeTwo: 'Flying',
    totalBaseStat: 400,
  },
  {
    id: '#086',
    sprite: getSpriteUrl(86),
    name: 'Seel',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 280,
  },
  {
    id: '#087',
    sprite: getSpriteUrl(87),
    name: 'Dewgong',
    typeOne: 'Water',
    typeTwo: 'Ice',
    totalBaseStat: 405,
  },
  {
    id: '#088',
    sprite: getSpriteUrl(88),
    name: 'Grimer',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 275,
  },
  {
    id: '#089',
    sprite: getSpriteUrl(89),
    name: 'Muk',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 400,
  },
  {
    id: '#090',
    sprite: getSpriteUrl(90),
    name: 'Shellder',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 280,
  },
  {
    id: '#091',
    sprite: getSpriteUrl(91),
    name: 'Cloyster',
    typeOne: 'Water',
    typeTwo: 'Ice',
    totalBaseStat: 480,
  },
  {
    id: '#092',
    sprite: getSpriteUrl(92),
    name: 'Gastly',
    typeOne: 'Ghost',
    typeTwo: 'Poison',
    totalBaseStat: 275,
  },
  {
    id: '#093',
    sprite: getSpriteUrl(93),
    name: 'Haunter',
    typeOne: 'Ghost',
    typeTwo: 'Poison',
    totalBaseStat: 350,
  },
  {
    id: '#094',
    sprite: getSpriteUrl(94),
    name: 'Gengar',
    typeOne: 'Ghost',
    typeTwo: 'Poison',
    totalBaseStat: 425,
  },
  {
    id: '#095',
    sprite: getSpriteUrl(95),
    name: 'Onix',
    typeOne: 'Rock',
    typeTwo: 'Ground',
    totalBaseStat: 340,
  },
  {
    id: '#096',
    sprite: getSpriteUrl(96),
    name: 'Drowzee',
    typeOne: 'Psychic',
    typeTwo: null,
    totalBaseStat: 285,
  },
  {
    id: '#097',
    sprite: getSpriteUrl(97),
    name: 'Hypno',
    typeOne: 'Psychic',
    typeTwo: null,
    totalBaseStat: 410,
  },
  {
    id: '#098',
    sprite: getSpriteUrl(98),
    name: 'Krabby',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 300,
  },
  {
    id: '#099',
    sprite: getSpriteUrl(99),
    name: 'Kingler',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 425,
  },
  {
    id: '#100',
    sprite: getSpriteUrl(100),
    name: 'Voltorb',
    typeOne: 'Electric',
    typeTwo: null,
    totalBaseStat: 275,
  },
  {
    id: '#101',
    sprite: getSpriteUrl(101),
    name: 'Electrode',
    typeOne: 'Electric',
    typeTwo: null,
    totalBaseStat: 400,
  },
  {
    id: '#102',
    sprite: getSpriteUrl(102),
    name: 'Exeggcute',
    typeOne: 'Grass',
    typeTwo: 'Psychic',
    totalBaseStat: 280,
  },
  {
    id: '#103',
    sprite: getSpriteUrl(103),
    name: 'Exeggutor',
    typeOne: 'Grass',
    typeTwo: 'Psychic',
    totalBaseStat: 455,
  },
  {
    id: '#104',
    sprite: getSpriteUrl(104),
    name: 'Cubone',
    typeOne: 'Ground',
    typeTwo: null,
    totalBaseStat: 270,
  },
  {
    id: '#105',
    sprite: getSpriteUrl(105),
    name: 'Marowak',
    typeOne: 'Ground',
    typeTwo: null,
    totalBaseStat: 345,
  },
  {
    id: '#106',
    sprite: getSpriteUrl(106),
    name: 'Hitmonlee',
    typeOne: 'Fighting',
    typeTwo: null,
    totalBaseStat: 345,
  },
  {
    id: '#107',
    sprite: getSpriteUrl(107),
    name: 'Hitmonchan',
    typeOne: 'Fighting',
    typeTwo: null,
    totalBaseStat: 345,
  },
  {
    id: '#108',
    sprite: getSpriteUrl(108),
    name: 'Lickitung',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 310,
  },
  {
    id: '#109',
    sprite: getSpriteUrl(109),
    name: 'Koffing',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 295,
  },
  {
    id: '#110',
    sprite: getSpriteUrl(110),
    name: 'Weezing',
    typeOne: 'Poison',
    typeTwo: null,
    totalBaseStat: 420,
  },
  {
    id: '#111',
    sprite: getSpriteUrl(111),
    name: 'Rhyhorn',
    typeOne: 'Ground',
    typeTwo: 'Rock',
    totalBaseStat: 315,
  },
  {
    id: '#112',
    sprite: getSpriteUrl(112),
    name: 'Rhydon',
    typeOne: 'Ground',
    typeTwo: 'Rock',
    totalBaseStat: 440,
  },
  {
    id: '#113',
    sprite: getSpriteUrl(113),
    name: 'Chansey',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 415,
  },
  {
    id: '#114',
    sprite: getSpriteUrl(114),
    name: 'Tangela',
    typeOne: 'Grass',
    typeTwo: null,
    totalBaseStat: 395,
  },
  {
    id: '#115',
    sprite: getSpriteUrl(115),
    name: 'Kangaskhan',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 410,
  },
  {
    id: '#116',
    sprite: getSpriteUrl(116),
    name: 'Horsea',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 270,
  },
  {
    id: '#117',
    sprite: getSpriteUrl(117),
    name: 'Seadra',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 395,
  },
  {
    id: '#118',
    sprite: getSpriteUrl(118),
    name: 'Goldeen',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 285,
  },
  {
    id: '#119',
    sprite: getSpriteUrl(119),
    name: 'Seaking',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 385,
  },
  {
    id: '#120',
    sprite: getSpriteUrl(120),
    name: 'Staryu',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 285,
  },
  {
    id: '#121',
    sprite: getSpriteUrl(121),
    name: 'Starmie',
    typeOne: 'Water',
    typeTwo: 'Psychic',
    totalBaseStat: 435,
  },
  {
    id: '#122',
    sprite: getSpriteUrl(122),
    name: 'Mr. Mime',
    typeOne: 'Psychic',
    typeTwo: 'Fairy',
    totalBaseStat: 340,
  },
  {
    id: '#123',
    sprite: getSpriteUrl(123),
    name: 'Scyther',
    typeOne: 'Bug',
    typeTwo: 'Flying',
    totalBaseStat: 420,
  },
  {
    id: '#124',
    sprite: getSpriteUrl(124),
    name: 'Jynx',
    typeOne: 'Ice',
    typeTwo: 'Psychic',
    totalBaseStat: 340,
  },
  {
    id: '#125',
    sprite: getSpriteUrl(125),
    name: 'Electabuzz',
    typeOne: 'Electric',
    typeTwo: null,
    totalBaseStat: 395,
  },
  {
    id: '#126',
    sprite: getSpriteUrl(126),
    name: 'Magmar',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 395,
  },
  {
    id: '#127',
    sprite: getSpriteUrl(127),
    name: 'Pinsir',
    typeOne: 'Bug',
    typeTwo: null,
    totalBaseStat: 430,
  },
  {
    id: '#128',
    sprite: getSpriteUrl(128),
    name: 'Tauros',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 450,
  },
  {
    id: '#129',
    sprite: getSpriteUrl(129),
    name: 'Magikarp',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 185,
  },
  {
    id: '#130',
    sprite: getSpriteUrl(130),
    name: 'Gyarados',
    typeOne: 'Water',
    typeTwo: 'Flying',
    totalBaseStat: 480,
  },
  {
    id: '#131',
    sprite: getSpriteUrl(131),
    name: 'Lapras',
    typeOne: 'Water',
    typeTwo: 'Ice',
    totalBaseStat: 450,
  },
  {
    id: '#132',
    sprite: getSpriteUrl(132),
    name: 'Ditto',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 240,
  },
  {
    id: '#133',
    sprite: getSpriteUrl(133),
    name: 'Eevee',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 280,
  },
  {
    id: '#134',
    sprite: getSpriteUrl(134),
    name: 'Vaporeon',
    typeOne: 'Water',
    typeTwo: null,
    totalBaseStat: 430,
  },
  {
    id: '#135',
    sprite: getSpriteUrl(135),
    name: 'Jolteon',
    typeOne: 'Electric',
    typeTwo: null,
    totalBaseStat: 430,
  },
  {
    id: '#136',
    sprite: getSpriteUrl(136),
    name: 'Flareon',
    typeOne: 'Fire',
    typeTwo: null,
    totalBaseStat: 430,
  },
  {
    id: '#137',
    sprite: getSpriteUrl(137),
    name: 'Porygon',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 310,
  },
  {
    id: '#138',
    sprite: getSpriteUrl(138),
    name: 'Omanyte',
    typeOne: 'Rock',
    typeTwo: 'Water',
    totalBaseStat: 300,
  },
  {
    id: '#139',
    sprite: getSpriteUrl(139),
    name: 'Omastar',
    typeOne: 'Rock',
    typeTwo: 'Water',
    totalBaseStat: 425,
  },
  {
    id: '#140',
    sprite: getSpriteUrl(140),
    name: 'Kabuto',
    typeOne: 'Rock',
    typeTwo: 'Water',
    totalBaseStat: 300,
  },
  {
    id: '#141',
    sprite: getSpriteUrl(141),
    name: 'Kabutops',
    typeOne: 'Rock',
    typeTwo: 'Water',
    totalBaseStat: 430,
  },
  {
    id: '#142',
    sprite: getSpriteUrl(142),
    name: 'Aerodactyl',
    typeOne: 'Rock',
    typeTwo: 'Flying',
    totalBaseStat: 440,
  },
  {
    id: '#143',
    sprite: getSpriteUrl(143),
    name: 'Snorlax',
    typeOne: 'Normal',
    typeTwo: null,
    totalBaseStat: 430,
  },
  {
    id: '#144',
    sprite: getSpriteUrl(144),
    name: 'Articuno',
    typeOne: 'Ice',
    typeTwo: 'Flying',
    totalBaseStat: 485,
  },
  {
    id: '#145',
    sprite: getSpriteUrl(145),
    name: 'Zapdos',
    typeOne: 'Electric',
    typeTwo: 'Flying',
    totalBaseStat: 490,
  },
  {
    id: '#146',
    sprite: getSpriteUrl(146),
    name: 'Moltres',
    typeOne: 'Fire',
    typeTwo: 'Flying',
    totalBaseStat: 495,
  },
  {
    id: '#147',
    sprite: getSpriteUrl(147),
    name: 'Dratini',
    typeOne: 'Dragon',
    typeTwo: null,
    totalBaseStat: 250,
  },
  {
    id: '#148',
    sprite: getSpriteUrl(148),
    name: 'Dragonair',
    typeOne: 'Dragon',
    typeTwo: null,
    totalBaseStat: 350,
  },
  {
    id: '#149',
    sprite: getSpriteUrl(149),
    name: 'Dragonite',
    typeOne: 'Dragon',
    typeTwo: 'Flying',
    totalBaseStat: 500,
  },
  {
    id: '#150',
    sprite: getSpriteUrl(150),
    name: 'Mewtwo',
    typeOne: 'Psychic',
    typeTwo: null,
    totalBaseStat: 590,
  },
  {
    id: '#151',
    sprite: getSpriteUrl(151),
    name: 'Mew',
    typeOne: 'Psychic',
    typeTwo: null,
    totalBaseStat: 500,
  },
];
